version: "3.8"
services:

  db:
    image: postgres:15rc2-alpine
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: mentorship
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432"

  server:
    image: iservice_mentorship:v2.0.1-dev
    container_name: s-master
    environment:
      NODE_ENV: development
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  node_modules:
  pgdata: